# Gemfile
source "https://rubygems.org"

ruby "2.1.5"
gem "sass", "3.4.19"
gem 'sass-globbing', '~> 1.1.1'
gem "compass", "~> 1.0.3"
gem 'modular-scale', '~> 2.1.1'
gem "susy", "~> 2.2.7"
gem "ffi", "1.9.3"