packery.group.*:
  type: config_entity
  label: 'Group'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    settings:
      type: mapping 
      label: 'Settings'
      mapping:
        images_loaded:
          type: boolean
          label: 'imagesLoaded'
          text: 'Provides support for imagesLoaded plugin.'
        container_style:
          type: string
          label: 'Container style'
          text: 'CSS styles that are applied to the container element. To disable Packery from setting any CSS to the container element, set NULL.'
        column_width:
          type: string
          label: 'Column width'
          text: 'The width of a column of a horizontal grid. When set, Packery will align item elements horizontally to this grid.'
        gutter:
          type: string
          label: 'Gutter'
          text: 'The space between item elements, both vertically and horizontally.'
        percent_position:
          type: boolean
          label: 'Percent position'
          text: 'Will set item position in percent values, rather than pixel values. percentPosition works well with percent-width items, as items will not transition their position on resize.'
        is_horizontal:
          type: boolean
          label: 'Is horizontal'
          text: 'Arranges items horizontally instead of vertically.'
        is_init_layout:
          type: boolean
          label: 'Is init layout'
          text: 'Enables layout on initialization. Set this to false to disable layout on initialization, so you can use methods or add events before the initial layout.'
        is_origin_left:
          type: boolean
          label: 'Is origin left'
          text: 'Controls the horizontal flow of the layout. By default, item elements start positioning at the left. Set to false for right-to-left layouts.'
        is_origin_top:
          type: boolean
          label: 'Is origin top'
          text: 'Controls the vertical flow of the layout. By default, item elements start positioning at the top. Set to false for bottom-up layouts. It’s like Tetris!'
        is_resize_bound:
          type: boolean
          label: 'Is resize bound'
          text: 'Binds layout only when the Packery instance is first initialized. You can bind and unbind resize layout afterwards with the bindResize and unbindResize methods.'
        item_selector:
          type: string
          label: 'Item selector'
          text: 'Specifies which child elements to be used as item elements. Setting itemSelector is always recommended. itemSelector is useful to exclude sizing elements.'
        row_height:
          type: integer
          label: 'Row height'
          text: 'Height of a row of a vertical grid. When set, Packery will align item elements vertically to this grid.'
        stamp:
          type: string
          label: 'Stamp'
          text: 'Specifies which elements are stamped within the layout.'
        transition_duration:
          type: string
          label: 'Transition duration'
          text: 'The time duration of transitions for item elements.'
